---
- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure Ansible dependencies are installed (CentOS 6).
      yum:
        name: libselinux-python
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int == 6


  roles:
    - role: geerlingguy.nfs

    - role: geerlingguy.packer_rhel
      when: ansible_os_family == 'RedHat'

    - role: geerlingguy.packer-debian
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Install Tools
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - lvm2
        - mc
        - git
        - wget
        - curl
        - vim
        - htop
      when: ansible_os_family == 'Debian'