---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian

  tasks:
    - name: Install Tools
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - lvm2
        - mc
        - git
        - wget
        - curl
        - vim