---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian

  tasks:
    - name: Install Tools
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - lvm2
        - mc
        - git
        - wget
        - curl
        - vim
        - htop
    
    - name: Add crontab entry to periodically remove Vagrant NAT default GW
      cron:
        name: "Remove Vagrant NAT default GW"
        user: "root"
        job: "ip r delete default dev enp0s3 >/dev/null 2>&1"
